export const PLACEHOLDERS: string[] = [
  'Szukaj: Portfel w parku',
  'Szukaj: Znajdź rower w centrum',
  'Szukaj: Klucze w bibliotece',
  'Szukaj: Kto znalazł mój plecak?',
  'Szukaj: Telefon zgubiony w kawiarni',
  'Szukaj: Okulary na przystanku',
  'Szukaj: Parasol w holu biura',
  'Szukaj: Pierścionek w szatni siłowni',
  'Szukaj: Szalik na stacji kolejowej',
  'Szukaj: Czapka w muzeum',
  'Szukaj: Zegarek na basenie',
  'Szukaj: Dokumenty w urzędzie',
  'Szukaj: Laptop w pociągu',
  'Szukaj: Kurtka w szatni',
  'Szukaj: Słuchawki w autobusie',
  'Szukaj: Portfel w sklepie',
  'Szukaj: Kluczyki na parkingu',
  'Szukaj: Torba na siłowni',
  'Szukaj: Rękawiczki w parku',
  'Szukaj: Dowód osobisty w banku',
  'Szukaj: Paszport na lotnisku',
  'Szukaj: Karta miejska w tramwaju',
  'Szukaj: Legitymacja w szkole',
  'Szukaj: Piórnik w klasie',
  'Szukaj: Buty w przebieralni',
  'Szukaj: Bluza na boisku',
  'Szukaj: Kosmetyczka w hotelu',
  'Szukaj: Ładowarka w kawiarni',
  'Szukaj: Powerbank w metrze',
  'Szukaj: Książka w bibliotece',
  'Szukaj: Zeszyt na uczelni',
  'Szukaj: Tablet w samolocie',
  'Szukaj: Aparat na plaży',
  'Szukaj: Dron w lesie',
  'Szukaj: Hulajnoga przed sklepem',
  'Szukaj: Rower pod blokiem',
  'Szukaj: Kask na ścieżce rowerowej',
  'Szukaj: Bidon na siłowni',
  'Szukaj: Termos w górach',
  'Szukaj: Pudełko śniadaniowe w szkole',
  'Szukaj: Teczka w biurze',
  'Szukaj: Segregator w archiwum',
  'Szukaj: Pilot w salonie',
  'Szukaj: Smoczek w wózku',
  'Szukaj: Zabawka na placu zabaw',
  'Szukaj: Płaszcz w teatrze',
  'Szukaj: Sweter w restauracji',
  'Szukaj: Koszula w pralni',
  'Szukaj: Spodnie w przymierzalni',
  'Szukaj: Sukienka na weselu',
  'Szukaj: Naszyjnik u jubilera',
  'Szukaj: Kolczyk na dywanie',
  'Szukaj: Bransoletka w łazience',
  'Szukaj: Pierścionek zaręczynowy',
  'Szukaj: Złoty łańcuszek',
  'Szukaj: Srebrny zegarek',
  'Szukaj: Smartwatch na ręce',
  'Szukaj: Czytnik ebooków w pociągu',
  'Szukaj: Konsola w plecaku',
  'Szukaj: Głośnik bluetooth na imprezie'
];

export function getRandomPlaceholder() {
  const i = Math.floor(Math.random() * PLACEHOLDERS.length);
  return PLACEHOLDERS[i];
}
